### ISSUE TITLE
Stoping a tween.

### ISSUE THREAD

**Issue by Ranguna** [oinkgms/uween#10]
Is there a way to stop a tween before it finishes ?
Pausing and adding another tween on top doesn't sound very efficient.

**Comment by beinteractive** [comment]
@Ranguna 

What do you really want to do?

- Stop and stay in current state -> Use `PauseTween`
- Stop and make 'to' state -> Use `SkipTween`

are recommended ways.

**Comment by Ranguna** [comment]
Both are good but if I, for example, use the first one, won't the state be paused in memory ?

Because if I want to resume it, I can but if I don't then the tween will just stay paused forever occupying preciouse memeory space.

Even worse, if I do this serveral times then there'd be loads of tween paused with no further use.
It'd be nice to have a way to free a tween from memory.

**Comment by beinteractive** [comment]
If you mind memory space, you can use simply `Destroy(GetComponent<TweenXXX>())`.
It same as normal Unity component.

**Comment by Ranguna** [comment]
Ok thanks !
