### ISSUE TITLE
You need modify your code api

### ISSUE THREAD

**Issue by zszen** [oinkgms/uween#3]
TweenX.add(target,second,moveAdditionValue);

I think the function should move target.x to target.x+moveAdditionValue

TweenX.to(target,second,moveToValue);

I think the function  should move target.x to moveAdditionValue

TweenX.to(target,second,moveToValue);
TweenX.by(target,second,moveByValue/moveAdditionValue);

**Comment by zszen** [comment]
TweenX.to(target,second,moveToValue);
TweenX.by(target,second,moveByValue/moveAdditionValue);

**Comment by beinteractive** [comment]
The interface is based on the Tweener, a traditional tweening library. I respect it.
