### ISSUE TITLE
TweenSXY after TweenX scale strange

### ISSUE THREAD

**Issue by zszen** [oinkgms/uween#7]
scale: TweenSXY.Add (unit.gameObject, 1f).FromBy (.1f).EaseOutElastic ()
move:TweenX.Add (unit.gameObject, GConf.Single().BoxesDragCancelTime).FromBy(GConf.Single().BoxesDragCancelPositionBy)

if just scale , it deal well. But scale after move will strange scale. Scale will bigger when running.

**Comment by beinteractive** [comment]
Please attach a simple project for reproducing the issue.
