### ISSUE TITLE
Using TweenCA causes Unity Editor crash

### ISSUE THREAD

**Issue by tyfkda** [oinkgms/uween#8]
Using `TweenCA` causes Unity Editor crash.

I have tested in a simple scene, which has a `Text` and attach a script like below:

```
using UnityEngine;
using Uween;

public class Fade : MonoBehaviour {
	void Start() {
		var targetColor = new Color(1, 0, 0, 1);

		// TweenC: Work
		//TweenC.Add(gameObject, 5.0f, targetColor);

		// TweenA: Work
		//TweenA.Add(gameObject, 5.0f, targetColor.a)
		//	.From(0);

		// TweenCA: Crash Unity editor.
		TweenCA.Add(gameObject, 5.0f, targetColor);
	}
}
```

FYI: `TweenC` and `TweenA` works fine.

Environment: Unity 5.5.0p3, Mac OSX (El Capitan)

**Comment by beinteractive** [comment]
I succeeded reproducing it. So you are right.
However it seems to be Unity's bug. Could you report the issue to Unity team?
